### ISSUE TITLE
商品类型页面, 数据显示前台按值匹配渲染

### ISSUE THREAD

**Issue by TotoTomatos** [Waite0603/shopMall_thymeleaf#2]
![image](https://github.com/Waite0603/shopMall_thymeleaf/assets/104059351/980449ef-21b3-44c5-a2ec-0dc35fd069ad)

![image](https://github.com/Waite0603/shopMall_thymeleaf/assets/104059351/27a36810-11cb-4ac4-85af-444bb6395043)

**Comment by Waite0603** [comment]
feat it in cb820f31e62f38963ee7d0e1bfddf401b28ebaf2
