### ISSUE TITLE
TODO: 实验报告前-

### ISSUE THREAD

**Issue by Waite0603** [Waite0603/shopMall_thymeleaf#5]
bug: getAllGoods 查询所有商品只能固定返回十条数据/ 新增商品前端未作唯一性校验

1. getAllGoods 查询所有商品只能固定返回十条数据
2. 新增商品前端未作唯一性校验, 当 code-商品号 重复时后端会报错且后端未拦截

TODO: 

1. 报告2 -> 商品增删改查 ? 商品分类页面 只对接了查询以及新增 其他未写 (可以写报告的话直接截图不管了)
2. 报告3 -> 消费者增删改查? 未完成!!! 可以直接改前端写法估计和报告2一样 (要改的话我明天直接改了)

![image](https://github.com/Waite0603/shopMall_thymeleaf/assets/75354124/d80fb387-12dc-4976-a1d6-83995f3f99be)

**Comment by TotoTomatos** [comment]
fix:bug

   1. getAllGoods 查询所有商品只能固定返回十条数据

       docs：根据需要传参pageNum , pageSize
![get](https://github.com/Waite0603/shopMall_thymeleaf/assets/104059351/8eb3ae4b-46de-4b17-9b0f-581c8b19f346)


   2. 新增商品前端未作唯一性校验, 当 code-商品号 重复时后端会报错且后端未拦截
     fix：后端进行重复校验：
 
![insert](https://github.com/Waite0603/shopMall_thymeleaf/assets/104059351/aa0cf593-d23f-4e09-b23e-bc9840714884)



  TODO:

     feat: 商品分类页面 前端差修改和删除 / 后端差删除接口 有api ----(报告已写可以不管)
![1716274360528](https://github.com/Waite0603/shopMall_thymeleaf/assets/104059351/8ecc4e20-4071-4622-9860-47a485ea777b)


     feat:商品管理页面api已经同步更新 报告缺图片可以写也可以不写
![1716274740116](https://github.com/Waite0603/shopMall_thymeleaf/assets/104059351/5c4c4a36-55bf-4547-912d-eb8285f2b145)
